### ISSUE TITLE
The action does not respect the From-To boundries

### ISSUE THREAD

**Issue by umbert-cobiro** [connorsmallman/github-jira-changelog-action#3]
Looks like a great action but can't manage to actually get it to work properly.
I keep getting all the commits, like from the begining of time, and is not respecting the `from` `to` flags that I pass in. Is there anything that has to be done in a special manner to make it respect those?

Thanks for the great work man.

**Comment by connorsmallman** [comment]
@umbert-cobiro Thanks! Could you provide an example of your github action yml?

**Comment by connorsmallman** [comment]
BTW it looks for the jira ticket id in the comment message not the branch name

**Comment by umbert-cobiro** [comment]
```
name: Release
on:
  push:
    branches:
      - HB-546
jobs:
  create-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Version
        run: echo ::set-env name=VERSION::1.1.1
      - name: Changelog
        id: changelog
        uses: connorsmallman/github-jira-changelog-action@v1.1.1
        with:
          jira_host: 'XXX.atlassian.net'
          jira_email: ${{secrets.JIRA_API_KEY}}
          jira_token: ${{secrets.JIRA_API_SECRET}}
          jira_base_url: ${{secrets.JIRA_URL}}
          source_control_range_from: 'develop'
          source_control_range_to: 'HB-546'
      - name: 'Get Previous tag'
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: 'Get next minor version'
        id: semver
        uses: 'WyriHaximus/github-action-next-semvers@v1'
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          body: "${{ steps.changelog.outputs.changelog_message }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.semver.outputs.patch }}
          allowUpdates: true
          draft: true
```
